import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import QRCode from "qrcode";
import imageBase64 from "@/images/feeds-croped.png";

// ---------- EXCEL EXPORT ----------
export const exportStoreComparisonToExcel = (selectedNames, reportData) => {
  if (!reportData || !reportData.rows || !reportData.stores) return;

  const stores = reportData.stores;

  // Header rows
  const companyRow = ["Feed Bazaar"];
  const titleRow = ["Store Comparison Report"];

  // Column Headers (Multi-level)
  const header1 = ["S.No", "Date"];
  const header2 = ["", ""]; // Sub-headers placeholders

  stores.forEach((store) => {
    header1.push(store.name, "", ""); // Blank strings for merged cells spanning store
    header2.push("Sales", "Change", "Accum.");
  });

  const bodyRows = reportData.rows.map((row) => {
    const excelRow = [row.sNo, row.date];
    stores.forEach((store) => {
      const storeData = row.stores?.[store.id] || {};
      excelRow.push(
        storeData.sales ?? 0,
        storeData.increaseOrDecrease ?? 0,
        storeData.accumulation ?? 0
      );
    });
    return excelRow;
  });

  const ws = XLSX.utils.aoa_to_sheet([companyRow, titleRow, header1, header2, ...bodyRows]);

  // Merge cells for headers
  const totalCols = 2 + stores.length * 3;
  if (!ws['!merges']) ws['!merges'] = [];
  
  // Merge Company Heading
  ws['!merges'].push({ s: { r: 0, c: 0 }, e: { r: 0, c: totalCols - 1 } });
  // Merge Title
  ws['!merges'].push({ s: { r: 1, c: 0 }, e: { r: 1, c: totalCols - 1 } });
  
  // Merge Store Names
  stores.forEach((_, idx) => {
    const startCol = 2 + idx * 3;
    ws['!merges'].push({ s: { r: 2, c: startCol }, e: { r: 2, c: startCol + 2 } });
  });

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Store Comparison");
  XLSX.writeFile(wb, "StoreComparisonReport.xlsx");
};

// ---------- PDF EXPORT ----------
export const exportStoreComparisonToPDF = async (selectedNames, reportData) => {
  if (!reportData || !reportData.rows || !reportData.stores) return;

  const user = JSON.parse(localStorage.getItem("user"));
  const stores = reportData.stores;
  
  // Orientation: Landscape for multiple stores
  const doc = new jsPDF("l", "pt", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const currentDate = new Date();
  const formattedDate = currentDate.toLocaleString("en-IN", { timeZone: "Asia/Kolkata", hour12: true });
  
  const qrText = `Generated by : ${user?.name || 'User'}\nEmployee Id : ${user?.employeeId || 'N/A'}\nGenerated at: ${formattedDate}`;
  const qrBase64 = await QRCode.toDataURL(qrText);

  // Build head rows
  const firstHeadRow = [
    { content: "S.No", rowSpan: 2, styles: { halign: "center", valign: "middle" } },
    { content: "Date", rowSpan: 2, styles: { halign: "center", valign: "middle" } },
  ];
  
  stores.forEach((store) => {
    firstHeadRow.push({ content: store.name, colSpan: 3, styles: { halign: "center", valign: "middle" } });
  });

  const secondHeadRow = [];
  stores.forEach(() => {
    secondHeadRow.push({ content: "Sales", styles: { halign: "center" } });
    secondHeadRow.push({ content: "Change", styles: { halign: "center" } });
    secondHeadRow.push({ content: "Accum.", styles: { halign: "center" } });
  });

  // Body rows
  const bodyRows = reportData.rows.map((row) => {
    const tableRow = [row.sNo, row.date];
    stores.forEach((store) => {
      const storeData = row.stores?.[store.id] || {};
      tableRow.push(
        (storeData.sales ?? 0).toLocaleString('en-IN'),
        (storeData.increaseOrDecrease ?? 0).toLocaleString('en-IN'),
        (storeData.accumulation ?? 0).toLocaleString('en-IN')
      );
    });
    return tableRow;
  });

  const drawHeaderFooter = (data) => {
    const pageNumber = doc.internal.getCurrentPageInfo().pageNumber;
    const pageCount = doc.internal.getNumberOfPages();

    // HEADER
    if (imageBase64) doc.addImage(imageBase64, "PNG", 10, 10, 40, 20);
    if (qrBase64) doc.addImage(qrBase64, "PNG", pageWidth - 45, 10, 30, 30);

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Store Comparison Report", pageWidth / 2, 20, { align: "center" });

    doc.setDrawColor(0);
    doc.setLineWidth(0.2);
    doc.line(10, 40, pageWidth - 10, 40);

    // FOOTER
    doc.setDrawColor(0);
    doc.setLineWidth(0.1);
    doc.line(10, pageHeight - 30, pageWidth - 10, pageHeight - 30);

    doc.setFontSize(8);
    doc.setTextColor("#a92427");
    doc.text("© Feed Bazaar Private Limited", pageWidth / 2, pageHeight - 20, { align: "center" });
    doc.setTextColor(0);
    doc.text(`Page ${pageNumber} of ${pageCount}`, pageWidth - 50, pageHeight - 20);
  };

  autoTable(doc, {
    head: [firstHeadRow, secondHeadRow],
    body: bodyRows,
    startY: 50,
    theme: "grid",
    styles: { fontSize: 7, halign: "center", valign: "middle", cellPadding: 2 },
    headStyles: { fillColor: [0, 49, 118], textColor: 255, halign: "center", valign: "middle" }, // #003176
    didDrawPage: drawHeaderFooter,
    margin: { top: 50, bottom: 40 },
    tableWidth: "auto",
  });

  doc.save("StoreComparisonReport.pdf");
};
